[build-system]
requires = [
    "setuptools>=46",
    "wheel",
    "oldest-supported-numpy",
    "setuptools_scm",
    "setuptools_scm_git_archive"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
